[theme]
background = "#EFF1F5"
primary = "#4C4F69"
secondary = "#DC8A78"
title = "#40A02B"
playing = "#EFF1F5"
playing_selected = "#40A02B"
playing_bg = "#40A02B"
highlight = "#4C4F69"
highlight_bg = "#ACB0BE"
error = "#D20F39"
error_bg = "#DF8E1D"
statusbar = "#000000"
statusbar_progress = "#00AC4C"
statusbar_bg = "#00AC4C"
cmdline = "#179299"
cmdline_bg = "#CCD0DA"
